# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow


class Ui_MainWindow(QMainWindow):

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(551, 591)
        MainWindow.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        MainWindow.setFocusPolicy(QtCore.Qt.NoFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(20, 100, 511, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 511, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.instLabel = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.instLabel.setObjectName("instLabel")
        self.verticalLayout_4.addWidget(self.instLabel)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputFld = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.inputFld.sizePolicy().hasHeightForWidth())
        font = QtGui.QFont()
        font.setPointSize(11)
        self.inputFld.setFont(font)
        self.inputFld.setSizePolicy(sizePolicy)
        self.inputFld.setClearButtonEnabled(False)
        self.inputFld.setObjectName("inputFld")
        self.horizontalLayout.addWidget(self.inputFld)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.clearBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.clearBtn.setObjectName("clearBtn")
        self.verticalLayout.addWidget(self.clearBtn)
        self.solveBtn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.solveBtn.setObjectName("SolveBtn")
        self.verticalLayout.addWidget(self.solveBtn)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 120, 511, 251))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lbl_routhhurwitz = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_routhhurwitz.setFont(font)
        self.lbl_routhhurwitz.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.lbl_routhhurwitz.setObjectName("lbl_routhhurwitz")
        self.verticalLayout_5.addWidget(self.lbl_routhhurwitz)
        self.routhTbl = QtWidgets.QTableWidget(self.verticalLayoutWidget_2)
        self.routhTbl.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.routhTbl.setObjectName("routhTbl")
        self.routhTbl.setColumnCount(0)
        self.routhTbl.setRowCount(0)
        self.verticalLayout_5.addWidget(self.routhTbl)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(20, 370, 511, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 390, 511, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignLeading | QtCore.Qt.AlignLeft | QtCore.Qt.AlignVCenter)
        self.label_2.setObjectName("label_2")
        self.outputTbl = QtWidgets.QTableWidget(self.centralwidget)

        self.outputTbl.setGeometry(QtCore.QRect(20, 420, 511, 111))
        self.outputTbl.setRowCount(3)
        self.outputTbl.setColumnCount(3)
        self.outputTbl.setObjectName("outputTbl")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 550, 131, 16))
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Routh-Hurwitz Table"))
        self.instLabel.setText(_translate("MainWindow", "Input coefficients separated by comma in descending order. "))
        self.clearBtn.setText(_translate("MainWindow", "Clear"))
        self.solveBtn.setText(_translate("MainWindow", "Solve"))
        self.lbl_routhhurwitz.setText(_translate("MainWindow", "Routh-Hurwitz Table"))
        self.label_2.setText(_translate("MainWindow", "Results"))
        self.label.setText(_translate("MainWindow", "Coded by: John Oliver Rubi"))
        self.outputTbl.setHorizontalHeaderLabels(["Odd", "Even", "Total"])
        self.outputTbl.setVerticalHeaderLabels(["RHP", "LHP", "jw"])


